#include "photos_app.h"

#include <lvgl.h>

#include "config.h"
#include "photo_data/brunette_woman.h"
#include "photo_data/face_portrait.h"
#include "photo_data/forest.h"
#include "photo_data/gray_haired_man.h"
#include "photo_data/mountains.h"
#include "photo_data/night_sky.h"
#include "photo_data/ocean.h"
#include "photo_data/sunset.h"

// Real photos, not placeholders: eight CC0 (public domain) photos from
// Wikimedia Commons, cropped to 172x232 and dithered down to RGB565. This
// board has no filesystem/SD slot and no PNG/JPEG decoder wired into
// lv_conf.h, so each one is embedded as a raw lv_img_dsc_t
// (src/apps/photo_data/<name>.c - LV_IMG_CF_TRUE_COLOR, so LVGL draws it
// directly with no decode step) - about 78KB flash apiece, generated by a
// one-off conversion script (crop, Floyd-Steinberg dither to 5/6/5 bits),
// not stored in this repo.
//   - Sunset: "Tranquil Sunset Sky with Birds"
//   - Ocean: "Ocean waves rippling" (Unsplash)
//   - Mountains: "Mountain Landscape 2025"
//   - Forest: "Autumn Forest Path with Tall Trees"
//   - Night Sky: "Stars and Milky Way over Åbyfjorden" by W.carter
//   - Face Portrait: "Face portrait" (Unsplash)
//   - Brunette Woman: "Brunette woman portrait" (Unsplash)
//   - Gray-Haired Man: "Gray-haired man portrait" (Unsplash)
// All CC0-licensed on Wikimedia Commons, no attribution required.

namespace {

constexpr lv_coord_t AREA_TOP = 40;

lv_obj_t *photo_img = nullptr;
lv_obj_t *caption = nullptr;
lv_obj_t *dots_row = nullptr;

struct Photo {
  const char *name;
  const lv_img_dsc_t *src;
};

constexpr Photo PHOTOS[] = {
    {"Sunset", &sunset},
    {"Ocean", &ocean},
    {"Mountains", &mountains},
    {"Forest", &forest},
    {"Night Sky", &night_sky},
    {"Portrait", &face_portrait},
    {"Portrait", &brunette_woman},
    {"Portrait", &gray_haired_man},
};
constexpr size_t PHOTO_COUNT = sizeof(PHOTOS) / sizeof(PHOTOS[0]);

size_t photo_idx = 0;

void show_photo() {
  lv_img_set_src(photo_img, PHOTOS[photo_idx].src);
  lv_label_set_text_fmt(caption, "%s  (%d/%d)", PHOTOS[photo_idx].name, (int)photo_idx + 1, (int)PHOTO_COUNT);

  for (uint32_t i = 0; i < PHOTO_COUNT; i++) {
    lv_obj_t *dot = lv_obj_get_child(dots_row, i);
    bool active = (i == photo_idx);
    lv_obj_set_style_bg_color(dot, active ? lv_color_white() : lv_color_hex(0x555555), 0);
  }
}

void on_open(lv_obj_t *parent) {
  photo_idx = 0;

  caption = lv_label_create(parent);
  lv_obj_set_style_text_font(caption, &lv_font_montserrat_16, 0);
  lv_obj_set_style_text_color(caption, lv_color_hex(0xCCCCCC), 0);
  lv_obj_align(caption, LV_ALIGN_TOP_MID, 0, 12);

  // lv_img auto-sizes to the source's 172x232, matching this app's photo
  // area exactly - no scaling needed.
  photo_img = lv_img_create(parent);
  lv_obj_set_pos(photo_img, 0, AREA_TOP);
  lv_obj_clear_flag(photo_img, LV_OBJ_FLAG_SCROLLABLE);

  dots_row = lv_obj_create(parent);
  lv_obj_set_size(dots_row, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
  lv_obj_set_style_bg_opa(dots_row, LV_OPA_TRANSP, 0);
  lv_obj_set_style_border_width(dots_row, 0, 0);
  lv_obj_set_style_pad_all(dots_row, 0, 0);
  lv_obj_set_style_pad_column(dots_row, 6, 0);
  lv_obj_set_flex_flow(dots_row, LV_FLEX_FLOW_ROW);
  lv_obj_clear_flag(dots_row, LV_OBJ_FLAG_SCROLLABLE);
  lv_obj_align(dots_row, LV_ALIGN_BOTTOM_MID, 0, -34);
  for (size_t i = 0; i < PHOTO_COUNT; i++) {
    lv_obj_t *d = lv_obj_create(dots_row);
    lv_obj_set_size(d, 6, 6);
    lv_obj_set_style_radius(d, LV_RADIUS_CIRCLE, 0);
    lv_obj_set_style_border_width(d, 0, 0);
    lv_obj_set_style_bg_opa(d, LV_OPA_COVER, 0);
    lv_obj_clear_flag(d, LV_OBJ_FLAG_SCROLLABLE);
  }

  lv_obj_t *hint = lv_label_create(parent);
  lv_label_set_text(hint, ACTION_WORD ": next  |  " HOME_HINT);
  lv_obj_set_style_text_font(hint, &lv_font_montserrat_14, 0);
  lv_obj_set_style_text_color(hint, lv_color_hex(0x555555), 0);
  lv_obj_align(hint, LV_ALIGN_BOTTOM_MID, 0, -16);

  show_photo();
}

void on_close() {
  photo_img = nullptr;
  caption = nullptr;
  dots_row = nullptr;
}

void on_short_press() {
  photo_idx = (photo_idx + 1) % PHOTO_COUNT;
  show_photo();
}

}  // namespace

const AppDescriptor photos_app = {
    .name = "Photos",
    .icon_symbol = LV_SYMBOL_IMAGE,
    .icon_color = lv_color_hex(0xFF2D55),
    .on_open = on_open,
    .on_close = on_close,
    .on_short_press = on_short_press,
};
